# Generated by Django 4.1 on 2022-08-22 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_alter_comment_approved_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
